name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  actions: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build extension
        run: npm run build

      - name: Package extension zip
        run: npm run package

      - name: Extract version
        id: meta
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate release notes from CHANGELOG
        id: notes
        run: |
          node scripts/release-notes.js ${GITHUB_REF_NAME#v} > RELEASE_NOTES.md || echo "No notes generated" > RELEASE_NOTES.md
          echo 'notes<<EOF' >> $GITHUB_OUTPUT
          cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.notes }}
          files: |
            extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
